- name: Install lighttpd
  yum:
    name: lighttpd
    state: present

- name: Retrieve homework web site tarball from bogusapp s3 bucket
  aws_s3:
    bucket: "bogus-app-homework"
    object: /homework.tar.gz
    dest: "{{ staging_dir }}/homework.tar.gz"
    mode: get
    aws_access_key: AKIAJH2C7CAWKL7BLTBA
    aws_secret_key: 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
    region: us-west-2
