- name: Install lighttpd
  yum:
    name: lighttpd
    state: present

- name: Retrieve homework web site tarball from bogusapp s3 bucket
  connection : local
  s3:
    bucket: bogus-app-homework
    object: homework.tar.gz
    dest: "{{ staging_dir }}/homework.tar.gz"
    mode: get
    aws_access_key:  AKIAI2DB7HIYHKOH2HXA
    aws_secret_key:  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
    region: us-west-2

- name: Creates directory
  file:
    path: /srv/bogusapp
    state: directory
    owner: "{{ lighttpd_user }}"
    group: "{{ lighttpd_group }}"
    mode: 0775

- name: Extract homework.tar.gz.tgz
  unarchive:
    src: "{{ staging_dir }}/homework.tar.gz"
    dest: /srv/bogusapp/
#    notify: restart lighttpd
