- name: Install lighttpd
  yum:
    name: lighttpd
    state: present

- name: Copy main configuration for lighttpd
  template: src=simple-lighttpd.conf.j2 dest=/etc/lighttpd/lighttpd.conf

- name: Copy named virutal host conf for
  template: src="{{ bogus_domain }}.conf.j2" dest="/etc/lighttpd/vhosts.d/{{ bogus_domain}}.conf"

- name: Retrieve homework web site tarball from s3 bucket
  connection : local
  s3:
    bucket: bogus-app-homework
    object: homework.tar.gz
    dest: "{{ staging_dir }}/homework.tar.gz"
    mode: get
    aws_access_key:  AKIAI2DB7HIYHKOH2HXA
    aws_secret_key:  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
    region: us-west-2

- name: Creates directory
  file:
    path: "/var/www/{{ bogus_domain }}"
    state: directory
    owner: "{{ lighttpd_user }}"
    group: "{{ lighttpd_group }}"
    mode: 0700

- name: Extract homework.tar.gz
  register: result
  notify: restart lighttpd
  unarchive:
    src: "{{ staging_dir }}/homework.tar.gz"
    dest: "/var/www/{{ bogus_domain }}/"
    owner: "{{ lighttpd_user }}"
    group: "{{ lighttpd_group }}"
    mode: 0744
