---
- name: Install lighttpd
  yum: name=lighttpd state=present

- name: Copy lighttpd configuration
  template: src=default.conf dest=/etc/lighttpd/conf.d/default.conf
  notify: restart lighttpd

- name: Retrieve homework web site tarball from bogusapp s3 bucket
  aws_s3:
    bucket: bogus-app-homework
    object: /homework.tar.gz
    dest: {{ staging_dir }}
    mode: get

- name: Extract homework.tar.gz.tgz
  unarchive:
    src: {{ staging_dir }}/homework.tar.gz.tgz
    dest: /srv/bogusapp/
  notify: restart lighttpd
