- name: insert iptables rule for lighttpd
  lineinfile: dest=/etc/sysconfig/iptables create=yes state=present regexp="{{ lighhttpd_port }}" insertafter="^:OUTPUT "
              line="-A INPUT -p tcp  --dport {{ lighttpd_port }} -j  ACCEPT"
  notify: restart iptables

- name: lighttp service state
  service: name=lighttpd state=started enabled=yes
